name: Maven Build

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      run-javacheck:
        description: 'Whether to run javacheck jobs'
        required: false
        type: string
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 17
      uses: actions/setup-java@v5.1.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: javacheck
      run: mvn -B package --file pom.xml
    - name: Upload ProjectTick JavaCheck Artifact
      uses: actions/upload-artifact@v5
      with:
        name: ProjectTick-JavaCheck-${{ github.run_id }}.jar
        path: javacheck/target/*.jar
