name: CI Zlib

# This workflow is called by ci-new.yml only.
# Do not add push/pull_request triggers here.
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      run-zlib:
        description: 'Whether to run zlib jobs'
        required: false
        type: string
        default: 'true'

jobs:
  build-zlib-main:
    if: inputs.run-zlib == 'true'
    timeout-minutes: 30
    name: ${{ matrix.os.name }} ${{ matrix.compiler }} ${{ matrix.arch.name }} ${{ matrix.std.name }}  ${{ matrix.builder }}
    runs-on: ${{ matrix.os.value }}
    defaults:
      run:
        working-directory: zlib
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Linux
            value: ubuntu-latest

          - name: MacOS
            value: macos-latest

          - name: Windows
            value: windows-latest
            cmake-opt: -G Ninja

        compiler:
          - gcc
          - clang

        arch:
          - name: 64-bit
            tag: amd64
            compiler-opt: -m64
            cmake-opt: -A x64

          - name: 32-bit
            tag: i386
            compiler-opt: -m32
            cmake-opt: -A Win32

        builder:
          - configure
          - cmake

        std:
          - name: c89
            value: c89
          - name: gnu89
            value: gnu89
          - name: c94
            value: iso9899:199409
          - name: c99
            value: c99
          - name: gnu99
            value: gnu99
          - name: c11
            value: c11
          - name: gnu11
            value: gnu11
          - name: c17
            value: c17
          - name: gnu17
            value: gnu17
          - name: c2x
            value: c2x
          - name: gnu2x
            value: gnu2x

        exclude:
          - { os:   { name: MacOS }, arch: { tag:  i386  } }
          - { os:   { name: Windows }, builder: configure }
          - { os:   { name: Windows }, arch: { tag:  i386  } }

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Install packages (Linux)
      if: runner.os == 'Linux' && matrix.arch.tag == 'i386'
      run: |
        sudo apt-get update
        sudo apt install gcc-multilib libc6-dev-i386-cross

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
          choco install --no-progress ninja

    - name: Generate project files (configure)
      if: matrix.builder == 'configure'
      run: |
        ./configure
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: -std=${{ matrix.std.value }} ${{ matrix.arch.compiler-opt }} -Werror -Wall -Wextra

    - name: Compile source code (configure)
      if: matrix.builder == 'configure'
      run: make -j2

    - name: Run test cases (configure)
      if: matrix.builder == 'configure'
      run: |
        make test
        make cover

    - name: Generate project files (cmake)
      if: matrix.builder == 'cmake'
      run: |
        cmake -S . -B ./build1 -D CMAKE_BUILD_TYPE=Release ${{ matrix.os.cmake-opt }} -DZLIB_BUILD_TESTING=OFF
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: -std=${{ matrix.std.value }} ${{ matrix.arch.compiler-opt }} -Werror -Wall -Wextra

    - name: Generate project files with tests (cmake)
      if: matrix.builder == 'cmake'
      run: |
        cmake -E rm -rf ./build2
        cmake -S . -B ./build2 -D CMAKE_BUILD_TYPE=Release ${{ matrix.os.cmake-opt }} -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=OFF -DCMAKE_C_FLAGS_RELEASE="-O2" -DCMAKE_CXX_FLAGS_RELEASE="-O2"
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: -std=${{ matrix.std.value }} ${{ matrix.arch.compiler-opt }} -Wall -Wextra

    - name: Compile source code (cmake)
      if: matrix.builder == 'cmake'
      run: cmake --build ./build1 --config Release

    - name: Compile source code with tests (cmake)
      if: matrix.builder == 'cmake'
      run: cmake --build ./build2 --config Release

    - name: Run test cases (cmake)
      if: matrix.builder == 'cmake'
      run: ctest ./build2 -C Release --output-on-failure --max-width 120

  build-zlib-msvc:
    if: inputs.run-zlib == 'true'
    timeout-minutes: 30
    name: ${{ matrix.os.name }} ${{ matrix.compiler }} ${{ matrix.arch.name }} ${{ matrix.std.name }}  ${{ matrix.builder }}
    runs-on: ${{ matrix.os.value }}
    defaults:
      run:
        working-directory: zlib
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            value: windows-latest

        compiler:
          - cl

        arch:
          - name: 32-bit
            value: -A Win32
          - name: 64-bit
            value: -A x64

        builder:
          - cmake

        std:
          - name: default
            value: ""
          - name: C11
            value: /std:c11
          - name: C17
            value: /std:c17
          - name: latest
            value: /std:clatest

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Generate project files (cmake)
      run: |
        cmake -S . -B ./build1 ${{ matrix.arch.value }} -D CMAKE_BUILD_TYPE=Release -DZLIB_BUILD_TESTING=OFF
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: /WX ${{ matrix.std.value }}

    - name: Generate project files with tests (cmake)
      run: |
        cmake -E rm -rf ./build2
        cmake -S . -B ./build2 ${{ matrix.arch.value }} -D CMAKE_BUILD_TYPE=Release -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=OFF -DCMAKE_C_FLAGS="" -DCMAKE_CXX_FLAGS=""
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.std.value }}

    - name: Compile source code (cmake)
      run: cmake --build ./build1 --config Release -v

    - name: Compile source code with tests(cmake)
      run: cmake --build ./build2 --config Release -v

    - name: Run test cases (cmake)
      run: ctest ./build2 -C Release --output-on-failure --max-width 120

  build-zlib-ci-cmake:
    if: inputs.run-zlib == 'true'
    timeout-minutes: 30
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: zlib
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu GCC
            os: ubuntu-latest
            compiler: gcc
            cflags: -Wall -Wextra
            pkgtgt: package package_source
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: Ubuntu GCC -O3
            os: ubuntu-latest
            compiler: gcc
            cflags: -O3 -Wall -Wextra
            pkgtgt: package package_source
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: Ubuntu Clang
            os: ubuntu-latest
            compiler: clang
            cflags: -Wall -Wextra
            pkgtgt: package package_source
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: Ubuntu Clang Debug
            os: ubuntu-latest
            compiler: clang
            cflags: -Wall -Wextra
            build-config: Debug
            pkgtgt: package package_source
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: Windows MSVC Win32
            os: windows-latest
            compiler: cl
            cflags: /W3
            cmake-args: -A Win32
            pkgtgt: PACKAGE

          - name: Windows MSVC Win64
            os: windows-latest
            compiler: cl
            cflags: /W3
            cmake-args: -A x64 -DMINIZIP_ENABLE_BZIP2=OFF
            pkgtgt: PACKAGE

          - name: Windows GCC
            os: windows-latest
            compiler: gcc
            cflags: -Wall -Wextra
            cmake-args: -G Ninja -DMINIZIP_ENABLE_BZIP2=OFF
            pkgtgt: package

          - name: macOS Clang
            os: macos-latest
            compiler: clang
            cflags: -Wall -Wextra
            pkgtgt: package
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: macOS GCC 13
            os: macos-latest
            compiler: gcc-13
            cflags: -Wall -Wextra
            pkgtgt: package
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: macOS GCC 14
            os: macos-latest
            compiler: gcc-14
            cflags: -Wall -Wextra
            pkgtgt: package
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

          - name: macOS GCC 15
            os: macos-latest
            compiler: gcc-15
            cflags: -Wall -Wextra
            pkgtgt: package
            cmake-args: -DMINIZIP_ENABLE_BZIP2=ON

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install --no-progress nsis

    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt install libbz2-dev
    - name: Generate project files
      run: |
        cmake -E rm -rf build
        cmake -S . -B build ${{ matrix.cmake-args }} -D CMAKE_BUILD_TYPE=${{ matrix.build-config || 'Release' }} -DZLIB_BUILD_MINIZIP=ON -DCMAKE_C_FLAGS="" -DCMAKE_CXX_FLAGS=""
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.cflags }}

    - name: Compile source code
      run: cmake --build build --config ${{ matrix.build-config || 'Release' }}

    - name: Run test cases
      run: ctest -C Release --output-on-failure --max-width 120
      working-directory: ${{ github.workspace }}/zlib/build

    - name: create packages
      run: cmake --build build --config ${{ matrix.build-config || 'Release' }} -t ${{ matrix.pkgtgt }}

    - name: Upload build errors
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      if: failure()
      with:
        name: zlib-${{ matrix.name }}-cmake
        path: |
          zlib/build/CMakeFiles/CMakeOutput.log
          zlib/build/CMakeFiles/CMakeError.log

  build-zlib-ci-configure:
    if: inputs.run-zlib == 'true'
    timeout-minutes: 30
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: zlib
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu GCC
            os: ubuntu-latest
            compiler: gcc
            configure-args: --warn

          - name: Ubuntu GCC OSB
            os: ubuntu-latest
            compiler: gcc
            configure-args: --warn
            build-dir: ../build
            src-dir: ../zlib

          - name: Ubuntu GCC ARM SF
            os: ubuntu-latest
            compiler: arm-linux-gnueabi-gcc
            configure-args: --warn
            chost: arm-linux-gnueabi
            packages: qemu-system qemu-user gcc-arm-linux-gnueabi libc-dev-armel-cross
            qemu-run: qemu-arm -L /usr/arm-linux-gnueabi

          - name: Ubuntu GCC ARM HF
            os: ubuntu-latest
            compiler: arm-linux-gnueabihf-gcc
            configure-args: --warn
            chost: arm-linux-gnueabihf
            packages: qemu-system qemu-user gcc-arm-linux-gnueabihf libc-dev-armhf-cross
            qemu-run: qemu-arm -L /usr/arm-linux-gnueabihf

          - name: Ubuntu GCC AARCH64
            os: ubuntu-latest
            compiler: aarch64-linux-gnu-gcc
            configure-args: --warn
            chost: aarch64-linux-gnu
            packages: qemu-system qemu-user gcc-aarch64-linux-gnu libc-dev-arm64-cross
            qemu-run: qemu-aarch64 -L /usr/aarch64-linux-gnu

          - name: Ubuntu GCC PPC
            os: ubuntu-latest
            compiler: powerpc-linux-gnu-gcc
            configure-args: --warn --static
            chost: powerpc-linux-gnu
            packages: qemu-system qemu-user gcc-powerpc-linux-gnu libc-dev-powerpc-cross
            qemu-run: qemu-ppc -L /usr/powerpc-linux-gnu
            cflags: -static
            ldflags: -static

          - name: Ubuntu GCC PPC64
            os: ubuntu-latest
            compiler: powerpc64-linux-gnu-gcc
            configure-args: --warn --static
            chost: powerpc-linux-gnu
            packages: qemu-system qemu-user gcc-powerpc64-linux-gnu libc-dev-ppc64-cross
            qemu-run: qemu-ppc64 -L /usr/powerpc64-linux-gnu
            cflags: -static
            ldflags: -static

          - name: Ubuntu GCC PPC64LE
            os: ubuntu-latest
            compiler: powerpc64le-linux-gnu-gcc
            configure-args: --warn
            chost: powerpc64le-linux-gnu
            packages: qemu-system qemu-user gcc-powerpc64le-linux-gnu libc-dev-ppc64el-cross
            qemu-run: qemu-ppc64le -L /usr/powerpc64le-linux-gnu

          - name: Ubuntu GCC S390X
            os: ubuntu-latest
            compiler: s390x-linux-gnu-gcc
            configure-args: --warn --static
            chost: s390x-linux-gnu
            packages: qemu-system qemu-user gcc-s390x-linux-gnu libc-dev-s390x-cross
            qemu-run: qemu-s390x -L /usr/s390x-linux-gnu
            cflags: -static
            ldflags: -static

          - name: macOS GCC 13
            os: macos-latest
            compiler: gcc-13
            configure-args: --warn

          - name: macOS GCC 14
            os: macos-latest
            compiler: gcc-14
            configure-args: --warn

          - name: macOS GCC 15
            os: macos-latest
            compiler: gcc-15
            configure-args: --warn

          - name: macOS Clang
            os: macos-latest
            compiler: clang
            configure-args: --warn

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux' && matrix.packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.packages }}

    - name: Generate project files
      run: |
        [ -d ${{ matrix.build-dir || '.' }} ] || mkdir ${{ matrix.build-dir || '.' }}
        cd ${{ matrix.build-dir || '.' }}
        ${{ matrix.src-dir || '.' }}/configure ${{ matrix.configure-args }}
      env:
        CC: ${{ matrix.compiler }}
        CFLAGS: ${{ matrix.cflags }}
        LDFLAGS: ${{ matrix.ldflags }}
        CHOST: ${{ matrix.chost }}

    - name: Compile source code
      run: make -j2
      working-directory: ${{ format('zlib/{0}', matrix.build-dir || '.') }}

    - name: Run test cases
      run: |
        make test
        make cover
      working-directory: ${{ format('zlib/{0}', matrix.build-dir || '.') }}
      env:
        QEMU_RUN: ${{ matrix.qemu-run }}

    - name: Upload build errors
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      if: failure()
      with:
        name: zlib-${{ matrix.name }}-configure
        path: |
          ${{ matrix.build-dir || '.' }}/configure.log

  build-zlib-MSys:
    if: inputs.run-zlib == 'true'
    timeout-minutes: 10
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        sys: [mingw32, mingw64, ucrt64, clang64]
    name: MSys - ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
        working-directory: zlib
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        fetch-depth: 0
    - name: Setup MSYS2
      uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: >-
          make
        pacboy: >-
          toolchain:p
          cmake:p
    - name: Configure
      run: |
        rm -rf "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build"
        cmake -G"Unix Makefiles" \
          -S "$(cygpath -u "$GITHUB_WORKSPACE")/zlib" \
          -B "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build" \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DMINIZIP_ENABLE_BZIP2=ON \
          -DCMAKE_C_FLAGS="" \
          -DCMAKE_CXX_FLAGS=""
    - name: Build
      run: cmake --build "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build" --config Release
    - name: Run tests
      run: ctest --output-on-failure --test-dir "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build" -C Release

  build-zlib-cygwin:
    if: inputs.run-zlib == 'true'
    timeout-minutes: 10
    strategy:
      fail-fast: false
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login -o igncr '{0}'
        working-directory: zlib
    name: Cygwin
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      with:
        fetch-depth: 0
    - name: Setup cygwin
      uses: cygwin/cygwin-install-action@7d2dc1e241644c3318bed9ec74115d1929baa681
      with:
        packages: >-
          cmake
          cygwin-devel
          gcc-core
          gcc-g++
          ninja
    - name: Configure
      run: |
        rm -rf "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build"
        cmake -S "$(cygpath -u "$GITHUB_WORKSPACE")/zlib" \
          -B "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build" \
          -DCMAKE_BUILD_TYPE=Release \
          -DZLIB_BUILD_MINIZIP=ON \
          -DMINIZIP_ENABLE_BZIP2=OFF \
          -DCMAKE_C_FLAGS="" \
          -DCMAKE_CXX_FLAGS="" \
          -G Ninja
    - name: Build
      run: cmake --build "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build" --config Release -v -j1
    - name: Run tests
      run: ctest --output-on-failure --test-dir "$(cygpath -u "$GITHUB_WORKSPACE")/zlib/build" -C Release
