name: Project Tick CI

on:
  merge_group:
  push:
    tags:
      - "*"
    branches:
      - "develop"
      - "release-*"
      - "qml_migration"
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Every hour
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened, edited]
  release:
    types: [ released ]
  workflow_run:
    workflows:
      - Reviewed
    types: [completed]
  pull_request_review:
    types: [submitted]
  branch_protection_rule:

concurrency:
  group: >
    projt-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs: