name: Nix

on:
  push:
    branches:
      - "develop"
      - "release-*"
    tags:
      - "*"
    paths:
      # File types
      - "**.cpp"
      - "**.h"
      - "**.java"
      - "**.ui"

      # Build files
      - "**.nix"
      - "nix/**"
      - "flake.lock"

      # Directories
      - "buildconfig/**"
      - "cmake/**"
      - "launcher/**"
      - "libraries/**"
      - "program_info/**"
      - "tests/**"

      # Files
      - "CMakeLists.txt"
      - "COPYING.md"

      # Workflows
      - ".github/workflows/nix.yml"
  pull_request:
    paths:
      # File types
      - "**.cpp"
      - "**.h"
      - "**.java"
      - "**.ui"

      # Build files
      - "**.nix"
      - "nix/**"
      - "flake.lock"

      # Directories
      - "buildconfig/**"
      - "cmake/**"
      - "launcher/**"
      - "libraries/**"
      - "program_info/**"
      - "tests/**"

      # Files
      - "CMakeLists.txt"
      - "COPYING.md"

      # Workflows
      - ".github/workflows/nix.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  DEBUG: ${{ github.ref_type != 'tag' }}

jobs:
  build:
    name: Build (${{ matrix.system }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            system: x86_64-linux

          - os: ubuntu-24.04-arm
            system: aarch64-linux

          - os: macos-15-intel
            system: x86_64-darwin

          - os: macos-26
            system: aarch64-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes


        # For PRs
      - name: Setup Nix Magic Cache
        if: ${{ github.event_name == 'pull_request' }}
        uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          diagnostic-endpoint: ""
          use-flakehub: false

        # For in-tree builds
      - name: Configure Nix binary cache
        run: |
          sudo mkdir -p /etc/nix
          {
            echo "substituters = https://cache.yongdohyun.org.tr https://cache.nixos.org"
            echo "trusted-public-keys = cache.yongdohyun.org.tr-1:HrpR1buYLhqx0ooS1rMgyHChoYf+faZm82hsIY6JS+s= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
            echo "experimental-features = nix-command flakes"
          } | sudo tee /etc/nix/nix.conf

      - name: Run Flake checks
        run: |
          nix flake check --print-build-logs --show-trace

      - name: Build debug package
        if: ${{ env.DEBUG == 'true' }}
        run: |
          nix build \
            --no-link --print-build-logs --print-out-paths \
            .#projtlauncher-debug >> "$GITHUB_STEP_SUMMARY"

      - name: Build release package
        if: ${{ env.DEBUG == 'false' }}
        env:
          TAG: ${{ github.ref_name }}
          SYSTEM: ${{ matrix.system }}
        run: |
          nix build --no-link --print-out-paths .#projtlauncher \
            | tee -a "$GITHUB_STEP_SUMMARY" \
  
      - name: Setup SSH
        if: ${{ github.event_name == 'push' }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CACHE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan cache.yongdohyun.org.tr >> ~/.ssh/known_hosts

      - name: Upload to private cache
        if: ${{ github.event_name == 'push' }}
        run: |
          rsync -avz \
            /nix/var/nix/binary-cache/ \
            root@cache.yongdohyun.org.tr:/var/www/cache/

      - name: Upload to private Nix cache
        if: ${{ env.DEBUG == 'false' }}
        env:
          PRIVATE_KEY: ${{ secrets.CACHE_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > signing.key
          chmod 600 signing.key

          # Configure Nix to sign with your key
          echo "secret-key = signing.key" >> ~/.config/nix/nix.conf

          # Build path list
          OUT=$(nix build --no-link .#projtlauncher --print-out-paths)

          echo "Uploading $OUT to cache.yongdohyun.org.tr"

          nix copy \
            --to "https://cache.yongdohyun.org.tr?trusted=yes" \
            $OUT
