name: Update Flake Lockfile

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    if: github.repository_owner == 'Project-Tick'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31

      - name: Use PAT
        run: echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          commit-msg: "chore(nix): update lockfile"
          pr-title: "chore(nix): update lockfile"
          pr-labels: |
            41.changelog:omit
